services:
    db:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=property_db
        container_name: mysql_db_container
        volumes:
            - pro_app_mysql_db:/var/lib/mysql
        healthcheck:
            #test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
    api:
        build:
            context: ./apis
        ports:
            - "5000:5000"
        environment:
            - DATABASE_URL=mysql://root:root@mysql_db_container:3306/property_db
            - JWT_SECRET=eww2442sfsffsf3131314fsfsfs4242
            - REDIS_HOST=redis_server
            - REDIS_PORT=6379
        restart: always
        container_name: api
        depends_on:
            db:
                condition: service_healthy
                restart: true
            nginx:
                condition: service_started
            redis:
                condition: service_started

        command: >
            sh -c "npx prisma migrate dev &&  npx prisma generate &&
             node app.js"
        #command: npx prisma migrate deploy

    client:
        build:
            context: ./frontend
        ports:
            - "4201:4201"
        container_name: client
        depends_on:
            - nginx
            - api
            #nginx:
            #    restart: always
            #    image: nginx:latest
            #    container_name: nginx
            #    volumes:
            #- "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
            #- ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            #        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

            #    ports:
            #        - "80:80"
    nginx:
        build:
            context: ./ngnixRoutes
        ports:
            - "80:80"
        container_name: nginx
        restart: always
    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8080:80"
        depends_on:
            db:
                condition: service_healthy
        container_name: phpmyadmin
        profiles:
            - dev

    redis:
        image: redis
        ports:
            - "6379:6379"
        container_name: redis_server
volumes:
    pro_app_mysql_db: {}
